import { HttpHeaders } from '@angular/common/http';

export const config = {
//  httpHeaders : { headers: new HttpHeaders({Authorization: 'Basic cmVzdHNlcnZpY2ViYXNpY2F1dGh1c2VyOlRMIzIwMTdAUkVTVCo4MzI0NjMkIw=='})},
  key_domain: 'domain',
  key_service_term: 'Service_Period',
  key_bgstatus: 'BG_Status',
  confirmation_fullpathname: 'home/_confirm',
  confirmation_shortpathname: '_confirm',
  shortkey_role_cba: 'cba',
  shortkey_role_fu: 'fu',
  shortkey_role_csst: 'csst',
  shortkey_role_cssm: 'cssm',
  shortkey_email_verificationemailaddress: 'eventgen28',
  shortkey_email_welcometocsstorcssm: 'eventgen32',
  shortkey_email_forgotpassword: 'eventgen15',
  shortkey_email_welcometofu: 'eventgen31',
  shortkey_email_welcometocba: 'eventgen30',
  shortkey_email_senttocsst: 'eventgen14',
  shortkey_email_senttocssm: 'eventgen13',
  shortkey_email_newservice_senttocssm: 'eventgen23',
  shortkey_email_newservice_senttocsst: 'eventgen24',
  shortkey_email_newservice_senttocssmapproved: 'eventgen21',
  shortkey_email_newservice_senttocssmreject: 'eventgen22',
  shortkey_email_rejected: 'eventgen11',
  shortkey_email_approved: 'eventgen12',
  shortkey_bg_sentocsst: 'csst-bgcheck',
  user_rolecode_cbu: 'CLIENT_BUSINESS_ADMINISTRATOR',
  user_rolecode_fu: 'FREELANCER_USER',
  user_rolecode_csct: 'CORE_SERVICE_SUPPORT_TEAM',
  user_rolecode_cscm: 'CORE_SERVICE_SUPPORT_MANAGER',
  bg_code_approved: 'BG_APPROVED',
  bg_code_rejected: 'BG_REJECTED',
  bg_code_senttoccsm: 'BG_SENTTOCSSM',
  bg_code_senttoccst: 'BG_SENTTOCSST',
  bg_code_incompleteprofile: 'BG_INCOMPLETEPROFILE',
  bg_code_completedprofile: 'BG_COMPLETEDPROFILE',
  default_avatar: 'https://platform-asserts.s3.amazonaws.com/Platform+Imgs/avatar1.png',
  default_prefer_lang: 'en',
  GOOGLE_MAPS_API_KEY: 'AIzaSyCaKbVhcX_22R_pRKDYuNA7vox-PtGaDkI',
  newservice_code_senttocssm: 'SENT_TO_CSSM',
  newservice_code_approved: 'APPROVED',
  newservice_code_rejected: 'REJECTED',


};


